version: '3.8'

services:
  redis:
    image: "redis:6.0-alpine"
    container_name: "redis"
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: "fastapi-app"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app   # Mount the current directory as a volume in the container
